language: node_js
node_js:
  - 12.16.3
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
    - 45.79.35.9
before_install:
  - openssl aes-256-cbc -K $encrypted_d79793b7f6d4_key -iv $encrypted_d79793b7f6d4_iv -in videogames-webpage.enc -out videogames-webpage -d
  - eval "$(ssh-agent -s)"
  - cp videogames-webpage ~/.ssh/videogames-webpage
  - chmod 600 ~/.ssh/videogames-webpage
  - ssh-add ~/.ssh/videogames-webpage
  - echo -e "Host 45.79.35.9\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: master
